# Generated by Django 2.2.19 on 2021-08-18 05:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20210818_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientamount',
            name='amount',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Количество'),
        ),
    ]
